### PR TITLE
fix: sh cacheinfo not found

### LINKED ISSUE #4: Command not found error
```
sh: cacheinfo: command not found
```

Reported by @awareness481

### PR DESCRIPTION
**Pull request by awareness481**
This fixes https://github.com/nickmccurdy/cacheinfo/issues/4 for me locally. :eyes: 

I "tested" it via running `npm i -g` inside the root folder of the repo.

### CODE REVIEW

**Comment by nickserv** [comment]
Thanks! This can also be shortened to `"bin": "dist/cli.js"`.

**Review by nickserv — APPROVED** [review]

**Comment by nickserv** [comment]
I also need to make that file executable for POSIX.

**Comment by awareness481** [comment]
> Thanks! This can also be shortened to `"bin": "dist/cli.js"`.

**Comment by awareness481** [comment]
> Thanks! This can also be shortened to `"bin": "dist/cli.js"`.

That works fine on my end ^^

**Comment by nickmccurdy** [comment]
This seems to be working even without executable flags, so I'll just merge it for now.

**Pull request merged**
